openapi: "3.0.0"
info:
  title: Ping API
  version: 1.0.0
  license:
    name: MIT
servers:
  - url: http://localhost:80
  - url: http://localhost:81

paths:
  /ping:
    get:
      summary: Health check
      operationId: ping
      responses:
        '200':
          description: Pong response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BaseResponse"
              example:
                status_message: success
                data: pong
components:
  schemas:
    BaseResponse:
      type: object
      properties:
        status_message:
          type: string
          example: success
        data:
          description: Dynamic payload
          x-go-type: interface{}
        total_data:
          type: integer
        url:
          type: string
        error:
          $ref: "#/components/schemas/ErrorLog"
      required:
        - status_message
        - data
        - total_data
        - url
    ErrorLog:
      type: object
      properties:
        message:
          description: User-facing error message
          type: string
        system_message:
          description: Internal or system-level error details
          type: string
        line:
          type: string
          description: Line where the error occurred
        filename:
          type: string
          description: Filename where the error occurred
        function:
          type: string
          description: Function name where the error occurred
      required:
        - message
        - system_message
        - line
        - filename
        - function