services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: FNL8qs3HuldRRl9P6YINySzQHp1EfxJr
      POSTGRES_DB: link_share
    ports:
      - "5432:5432"
    volumes:
      #- postgres_data:/var/lib/postgresql/data
      - ./misc/init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:7.4-alpine
    container_name: redis
    command: ["redis-server", "--requirepass", "AznRnqks3S1Ne5ZKZBrnLhFVLoqQMCOG"]
    environment:
      REDIS_PASSWORD: AznRnqks3S1Ne5ZKZBrnLhFVLoqQMCOG
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: FsyyxSX6exPHVwpQwhtraLyJbYhIfVEB
    ports:
      - "27017:27017"
    volumes:
      # - mongo_data:/data/db
      - ./misc/init-mongo.js:/docker-entrypoint-initdb.d/init.js
volumes:
  postgres_data:
  redis_data:
  mongo_data: