// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/google/wire"
	"linkshare/app/controllers"
	"linkshare/app/global/db"
	"linkshare/app/repositories/mongo_repo"
	"linkshare/app/repositories/sql_repo"
	"linkshare/app/routes"
	"linkshare/app/security"
	"linkshare/app/usecases"
)

// Injectors from wire.go:

func InitializeFiberServer(postgresParam db.PostgresParam, mongoParam db.MongoParam, redisParam db.RedisParam) *fiber.App {
	pgxIface := db.NewPostgresClient(postgresParam)
	iAuthRepository := sql_repo.NewAuthRepository(pgxIface)
	client := db.NewMongoClient(mongoParam)
	redisClient := db.NewRedisClient(redisParam)
	iAccessTokenSessionsRepository := mongo_repo.NewAccessTokenSessionRepository(client, redisClient)
	iRefreshTokenSessionsRepository := mongo_repo.NewRefreshTokenSessionRepository(client, redisClient)
	iJwtSecurity := security.NewJwtSecurity()
	iAuthUseCase := usecases.NewAuthUseCase(iAuthRepository, iAccessTokenSessionsRepository, iRefreshTokenSessionsRepository, iJwtSecurity)
	iAuthController := controllers.NewAuthController(iAuthUseCase)
	app := routes.NewRouter(iAuthController)
	return app
}

// wire.go:

var connectionSet = wire.NewSet(db.NewPostgresClient, db.NewMongoClient, db.NewRedisClient)

var controllerSet = wire.NewSet(controllers.NewAuthController)

var useCaseSet = wire.NewSet(usecases.NewAuthUseCase)

var repositorySet = wire.NewSet(sql_repo.NewAuthRepository, mongo_repo.NewAccessTokenSessionRepository, mongo_repo.NewRefreshTokenSessionRepository)

var securitySet = wire.NewSet(security.NewJwtSecurity)
